root: true
env:
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
settings:
  react:
    version: detect
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier/@typescript-eslint
  - "plugin:prettier/recommended"
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
rules:
  react/require-default-props: 0
  import/extensions: 0
